[package]
name = "bevy_geng_audio"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.12", default-features = false, features = ["bevy_asset"] }
geng-audio = "0.17"
anyhow = "1"
async-oneshot = "0.5"
once_cell = "1"
